# Generated by Django 5.0.3 on 2024-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinMarketCapMapping",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank", models.IntegerField(verbose_name="Rank")),
                ("name", models.CharField(verbose_name="Name")),
                ("symbol", models.CharField(verbose_name="Symbol")),
                ("slug", models.CharField(verbose_name="Slug")),
                ("is_active", models.IntegerField(verbose_name="Is Active")),
                (
                    "first_historical_data",
                    models.DateTimeField(verbose_name="First Historical Data"),
                ),
                (
                    "last_historical_data",
                    models.DateTimeField(verbose_name="Last Historical Data"),
                ),
                ("platform", models.CharField(verbose_name="Platform")),
            ],
        ),
    ]
