# Generated by Django 5.0.3 on 2024-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0002_coinmarketcapmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinMarketCapMetaData",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(verbose_name="Name")),
                ("symbol", models.CharField(verbose_name="Symbol")),
                ("category", models.CharField(verbose_name="Category")),
                ("description", models.CharField(verbose_name="Description")),
                ("slug", models.CharField(verbose_name="Slug")),
                ("logo", models.CharField(verbose_name="Logo")),
                ("subreddit", models.CharField(verbose_name="Sub Reddit")),
                ("notice", models.CharField(verbose_name="Notice")),
                ("tags", models.CharField(verbose_name="Tags")),
                ("tag_names", models.CharField(verbose_name="Tag Names")),
                ("tag_groups", models.CharField(verbose_name="Tag Groups")),
            ],
        ),
    ]
