# Generated by Django 5.0.3 on 2024-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0003_coinmarketcapmetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinmarketcapmapping",
            name="platform",
            field=models.CharField(null=True, verbose_name="Platform"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="category",
            field=models.CharField(null=True, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="description",
            field=models.CharField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="logo",
            field=models.CharField(null=True, verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="notice",
            field=models.CharField(null=True, verbose_name="Notice"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="subreddit",
            field=models.CharField(null=True, verbose_name="Sub Reddit"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="tag_groups",
            field=models.CharField(null=True, verbose_name="Tag Groups"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="tag_names",
            field=models.CharField(null=True, verbose_name="Tag Names"),
        ),
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="tags",
            field=models.CharField(null=True, verbose_name="Tags"),
        ),
    ]
