# Generated by Django 5.0.3 on 2024-03-24 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0005_coinmarketcapmapping_expiration_tmstmp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coinmarketcapmapping",
            name="expiration_tmstmp",
        ),
        migrations.RemoveField(
            model_name="coinmarketcapmetadata",
            name="expiration_tmstmp",
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="contract_address",
            field=models.CharField(null=True, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="date_added",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date Added"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="date_launched",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date Launched"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="infinite_supply",
            field=models.BooleanField(default=False, verbose_name="Is Hidden"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Is Hidden"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="platform",
            field=models.CharField(null=True, verbose_name="Platform"),
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="self_reported_circulating_supply",
            field=models.FloatField(
                null=True, verbose_name="Self Reported Circulating Supply"
            ),
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="self_reported_market_cap",
            field=models.FloatField(null=True, verbose_name="Self Reported Market Cap"),
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="self_reported_tags",
            field=models.CharField(null=True, verbose_name="Self Reported Tags"),
        ),
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="twitter_username",
            field=models.CharField(null=True, verbose_name="Twitter Username"),
        ),
    ]
