# Generated by Django 5.0.3 on 2024-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0006_remove_coinmarketcapmapping_expiration_tmstmp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinmarketcapmetadata",
            name="urls",
            field=models.CharField(null=True, verbose_name="Urls"),
        ),
    ]
