# Generated by Django 5.0.3 on 2024-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0007_coinmarketcapmetadata_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="is_hidden",
            field=models.IntegerField(verbose_name="Is Hidden"),
        ),
    ]
