# Generated by Django 5.0.3 on 2024-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmetrics", "0008_alter_coinmarketcapmetadata_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinmarketcapmetadata",
            name="date_launched",
            field=models.DateField(null=True, verbose_name="Date Launched"),
        ),
    ]
